version: "3.8"
services:
  db:
    image: postgres
    networks:
      new:
        aliases:
          - database
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      #POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5432:5432
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER} -d findadoc
      interval: 10s
      timeout: 3s
      retries: 5

    volumes:
      - pgdata:/var/lib/postgresql/data # persist data even if container shuts down
  migrate:
    image: migrate/migrate
    networks:
      - new
    volumes:
      - ./db/migrations:/migrations
    command: ["-path", "/migrations", "-database", "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@findadoc:5432/${POSTGRES_DB}?sslmode=disable", "up"]
    links:
      - db
    depends_on:
      db:
        condition: service_healthy
  api:
    build: 
      dockerfile: Dockerfile
      context: .
    networks:
      - new
    ports: 
      - 8080:8080
    volumes:
      - files:/files # persist data even if container shuts down
    links:
      - db
    depends_on:
      - migrate
      - db

volumes:
  pgdata:
  files:
  migrations:
  
networks:
      new: