version: "3.8"
services:
  db:
    image: postgres:14-alpine
    networks:
      new:
        aliases:
          - database
    env_file:
      - .env
    ports:
      - ${POSTGRES_PORT}:5432
    build:
      dockerfile: docker/DockerfileDB
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER} -d findadoc
      interval: 10s
      timeout: 3s
      retries: 5

    volumes:
      - pgdata:/var/lib/postgresql/findadoc-data # persist data even if container shuts down
#migrate:
#   image: alpine
#   depends_on:
#     - db
#   env_file:
#     - .env
#   networks:
#     - new
#   volumes:
#     - ./prisma:/prisma

volumes:
  pgdata:


networks:
  new:
