version: "3.8"
services:
  db:
    image: postgres:14-alpine
    networks:
      new:
        aliases:
          - database
    env_file:
      - .env
    ports:
      - ${POSTGRES_PORT}:5432
    healthcheck:
      test:
        - pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}
      interval: 10s
      timeout: 3s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/findadoc-data # persist data even if container shuts down
  db-cofigure:
    image: postgres:14-alpine
    depends_on:
      - db
    networks:
      new:
        aliases:
          - database
    env_file:
      - .env
    entrypoint: /docker/db-init.sh
    healthcheck:
      test:
        - postgres psql -c "SELECT datname FROM pg_catalog.pg_database WHERE datname='${SHADOW_DB}'"
      interval: 10s
      timeout: 3s
      retries: 5
    volumes:
      - ./docker:/docker
  migrate:
    image: node:18.12.1-alpine
    depends_on:
      - db-configure
    env_file:
      - .env
    build:
      dockerfile: dockerfile/DockerfileMigrate
    networks:
      - new
    volumes:
      - ./prisma:/prisma

volumes:
  pgdata:


networks:
  new:
