version: "3.8"
services:
  db:
    image: postgres:14-alpine
    networks:
      new:
        aliases:
          - database
    env_file:
      - .env
    ports:
      - 5432:5432

    build:
      dockerfile: docker/DockerfileDB
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER} -d findadoc
      interval: 10s
      timeout: 3s
      retries: 5

    volumes:
      - pgdata:/var/lib/postgresql/findadoc-data # persist data even if container shuts down

volumes:
  pgdata:
  
networks:
      new: