version: "3.8"
services:
  db:
    image: postgres
    networks:
      new:
        aliases:
          - database
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      #POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5432:5432
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER} -d findadoc
      interval: 10s
      timeout: 3s
      retries: 5

    volumes:
      - pgdata:/var/lib/postgresql/data # persist data even if container shuts down


volumes:
  pgdata:
  
networks:
      new: