version: "3.8"
services:
  db:
    image: postgres:14-alpine
    networks:
      new:
        aliases:
          - database
    env_file:
      - .env
    ports:
      - ${POSTGRES_PORT}:5432
    healthcheck:
      test:
        - pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}
      interval: 10s
      timeout: 3s
      retries: 5

    volumes:
      - pgdata:/var/lib/postgresql/findadoc-data # persist data even if container shuts down
  migrate:
    image: node:18.12.1-alpine
    depends_on:
      - db
    env_file:
      - .env
    entrypoint: /docker/init-and-migrate.sh
    networks:
      - new
    volumes:
      - ./prisma:/prisma
      - ./docker:/docker

volumes:
  pgdata:


networks:
  new:
