version: "3.9"
services:
  db:
    build: 
      dockerfile: /docker/db/Dockerfile
      context: ./
    image: findadoc_postgres_db
    networks:
      - findadoc
    env_file:
      - .env
    ports:
      - 5400
      - ${POSTGRES_PORT}:${DOCKER_INTERNAL_PORT}
    # healthcheck:
    #   test:
    #     [
    #       "CMD",
    #       "return false"
    #       # "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"
    #     ]
      # interval: 10s
      # timeout: 3s
      # retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/findadoc-data # persist data even if container shuts down
  migrate:
    build: 
      dockerfile: /docker/prisma/Dockerfile
      context: ./
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${DOCKER_POSTGRES_HOST}:${DOCKER_INTERNAL_PORT}/${POSTGRES_DB}?schema=public
      - SHADOW_DB_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${DOCKER_POSTGRES_HOST}:${DOCKER_INTERNAL_PORT}/${SHADOW_DB}?schema=public
    links:
      - db
    networks:
      - findadoc
volumes:
  pgdata:
  status:

networks:
  findadoc: