#!/bin/sh

# load env variables
source ./.env

psql $POSTGRES_USER << EOF
CREATE DATABASE $POSTGRES_DB;
CREATE DATABASE $SHADOW_DB;
GRANT ALL PRIVILEGES ON DATABASE $POSTGRES_DB TO postgres;
GRANT ALL PRIVILEGES ON DATABASE $SHADOW_DB TO postgres;
EOF