import * as gqlType from './gqlTypes.js'

//Omit is how we can override a field from the inherited type. 
//In this instance, we want to use the dbSchema contact type instead of the gqlType contact type.
export type Facility = Omit<gqlType.Facility, 'contact'> & {
    contact: Contact
}

// Row shape as returned from Supabase "facilities" table (no healthcareProfessionalIds yet).
export type DbFacilityRow = Omit<gqlType.Facility, 'healthcareProfessionalIds'>

export interface DbHealthcareProfessionalRow {
    id: string
    names: LocalizedName[]
    degrees: Degree[]
    specialties: Specialty[]
    spoken_languages: gqlType.Locale[]
    accepted_insurance: Insurance[]
    additional_info_for_patients: string | null
    created_date: string
    updated_date: string
}

// ID generated by DB
export type HealthcareProfessionalInsertRow = Omit<DbHealthcareProfessionalRow, 'id'>

export type HealthcareProfessional =
    Omit<gqlType.HealthcareProfessional,
        'names' | 'specialties' | 'degrees' | 'acceptedInsurance'>
    & {
        names: LocalizedName[]
        specialties: Specialty[]
        degrees: Degree[]
        acceptedInsurance: Insurance[]
    }

export type Submission = Omit<gqlType.Submission, 'facility' | 'healthcareProfessionals'> & {
    facility: gqlType.FacilitySubmission | null
    healthcareProfessionals: gqlType.HealthcareProfessionalSubmission[]
}

export const SUBMISSION_STATUS = {
    PENDING: 'pending',
    UNDER_REVIEW: 'under_review',
    APPROVED: 'approved',
    REJECTED: 'rejected'
} as const

export type SubmissionStatusValue = typeof SUBMISSION_STATUS[keyof typeof SUBMISSION_STATUS]

export interface SubmissionRow {
    id: string
    status: SubmissionStatusValue
    googleMapsUrl: string
    healthcareProfessionalName: string
    spokenLanguages: gqlType.Locale[]
    autofillPlaceFromSubmissionUrl: boolean
    // Used for approvesubmission with partial data
    facility_partial: gqlType.FacilitySubmission | null
    healthcare_professionals_partial: gqlType.HealthcareProfessionalSubmission[] | null
    hps_id: string | null
    facilities_id: string | null
    notes: string | null
    createdDate: string
    updatedDate: string
}

// ID generated by DB
export type SubmissionInsertRow = Omit<SubmissionRow, 'id'>

export type AuditLog = Omit<gqlType.AuditLog, 'id' | 'updatedDate'>

export type AuditLogResult = {
    isSuccesful: boolean
}

export type Contact = gqlType.Contact
export type LocalizedName = gqlType.LocalizedName
export type Specialty = gqlType.Specialty
export type Degree = gqlType.Degree
export type Insurance = gqlType.Insurance
