services:
  findadoc-dev-server:
    container_name: findadoc-dev-server
    build: 
      context: ../
      dockerfile: docker/development/Dockerfile
    environment:
      - FIRESTORE_EMULATOR_HOST=db:3004
      - FIRESTORE_PROJECT_ID=find-a-doc-japan
      - SERVER_PORT=3000
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_started
    volumes:
      - ../src:/usr/src/app/src
      - ../yarn.lock:/usr/src/app/yarn.lock
      - ../package.json:/usr/src/app/package.json
  db:
    container_name: emulator
    build:
      context: ../
      dockerfile: docker/firebase-emulator/Dockerfile
    ports:
      - "3004:3004" #firestore
      - "3005:3005" #ui