server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: ${LOGGER_GRAFANA_URL}/loki/api/v1/push
    basic_auth:
      username: ${LOGGER_GRAFANA_USER_ID}
      password: ${LOGGER_GRAFANA_API_KEY}

scrape_configs:
  - job_name: findadoc-api
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
        filters:
          - name: name
            values: ["findadoc-api"]
    relabel_configs:
      - source_labels: ["__meta_docker_container_name"]
        regex: "/(.*)"
        target_label: container
      - target_label: app
        replacement: findadocjp
