name: reviewdog
on: 
  pull_request:
      types: [ready_for_review]
  
jobs:
  eslint:
    name: run eslint with reviewdog
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write 
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - uses: reviewdog/action-eslint@v1.16.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review # Change reporter.
          eslint_flags: '. --ext .js,.ts,.json'

