name: Typecheck

on:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  typecheck:
    name: Typecheck 🔎
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6
        with:
          persist-credentials: false
      - name: Install Yarn / Node ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
      - name: Install Dependencies
        run: yarn install --immutable
      - name: Run typecheck
        run: npx tsc --noEmit
